src/ServiceCrm/ProductBundle/Form/Type/SmartPhoneProductType.php
<?php


namespace ServiceCrm\ProductBundle\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class SmartPhoneProductType extends  AbstractType
{

	public function getName()
	{
		return 'product';
	}

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder->add('price', 'number', array(
			'virtual' => true,
		));
	}
}

src/ServiceCrm/ProductBundle/Resources/views/ProductAdmin/create_supplierselect.html.twig
{% extends '@SonataAdmin/CRUD/edit.html.twig' %}

{% block form %}

    <h1>{{ 'label.select_supplier' | trans() }}</h1>
    <ul>
        {% if suppliers|length > 0 %}
            {% for supplier in suppliers %}
                <li>
                    <a href="{{ admin.generateUrl('create', admin.persistentParameters | merge({ supplier: supplier.id })) }}">{{ supplier.name | trans() }}</a>
                </li>
            {% endfor %}
        {% else %}
            <div style="color:red">
                <b><li>Futár igénylése előtt kérem válasszon felhasználót akinek igényelni szeretné -> ( Felhasználók list/ Felahasználó / Futár igénylés )</li></b>
                <b><li>Ha választott felhasználót, de nem tud szolgáltatót kiválasztani, kérem a felhasználóhoz rendeljen hozzá egy szolgáltatót! ( Felhasználói profil )</li></b>
            </div>
        {% endif %}
    </ul>

{% endblock %}

src/ServiceCrm/ProductBundle/Resources/views/ProductAdmin/create_typeselect.html.twig
{% extends '@SonataAdmin/CRUD/edit.html.twig' %}

{% block form %}


    <h1>{{ 'label.select_product_type' | trans() }}</h1>
    <ul>
        {% for type in types %}
            <li>
                <a href="{{ admin.generateUrl('create', admin.persistentParameters | merge({ product_type: type.id })) }}">{{ type.name | trans() }}</a>
            </li>
        {% endfor %}
    </ul>


{% endblock %}